name: build-and-push

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag: ["alpine", "alpine-edge", "buster", "stretch"]
        include:
          - tag: "alpine"
            path: "./alpine/main"
          - tag:  "alpine-edge"
            path: "./alpine/edge"
          - tag: "buster"
            path: "./debian/buster"
          - tag: "stretch"
            path: "./debian/stretch"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.9
        with:
          versionSpec: '5.x'
        
      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.9
        
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.0.1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUBUSERNAME }}
          password: ${{ secrets.DOCKERHUBTOKEN }}
        
      - name: Build and Push with version
        uses: docker/build-push-action@v2.0.1
        with:
          tags: |
            mkodockx/docker-clamav:${{ steps.gitversion.outputs.MajorMinorPatch }}-${{ matrix.tag }}         
            mkodockx/docker-clamav:${{ matrix.tag }} 
          file: ${{ matrix.path }}/Dockerfile
          context: ${{ matrix.path }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          push: true
